
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  jpa:
   hibernate:
    ddl-auto: update
   database-platform: org.hibernate.dialect.PostgreSQL9Dialect
   show-sql: true

   