 
name: Maven-docker-acr-eks-cicd
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Setup jdk8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ GITHUB.WORKSPACE }}
          
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1

      - name: Build with Maven
        run: |
          mvn  package --file POS_DayClose/pom.xml
          mkdir staging && cp target/*.war staging
      
      - name: set up a cache for maven
        uses: actions/cache@v2
        with: 
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
          
      - name: persist workflow data as artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: staging
          
      
          
      
          
          
