 
name: Maven-docker-acr-eks-cicd
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
          
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.8.2
      
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'     
      - name: Docker inspect
        run: docker ps
      - name: 
         run apt-get install ping -y && ping localhost -p 5432
      - name: Build with Maven
        run: mvn -B package --file POS_DayClose/pom.xml
      - name: Build with Maven
        run: mvn -B package --file CustomerDetails/pom.xml
