 
name: Maven-docker-acr-eks-cicd
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
          
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.8.2
      
      - name: Install PostgeSQL
        run: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list' && wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -  && sudo apt-get update && sudo apt-get -y install postgresql

      - name: Ping to PostgreSQL
        run: sudo apt-get -y install ping && ping -c 5 localhost -p 5432 
        
      - name: Build with Maven
        run: mvn -B package --file POS_DayClose/pom.xml
        
      - name: Build with Maven
        run: mvn -B package --file CustomerDetails/pom.xml
